apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"

      - job_name: "vdtops-api"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "my-app-dev-api.dev.svc.cluster.local:5000"
            labels:
              app: "vdtops-api"
              namespace: "dev"
