apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . | default .Chart.Name }}-api
  labels:
    app: {{ include "my-app.name" . | default .Chart.Name }}
    component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "my-app.name" . | default .Chart.Name }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "my-app.name" . | default .Chart.Name }}
        component: api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-api
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.api.containerPort }}"
            - name: APP_VERSION
              value: "{{ .Values.api.tag }}"
          livenessProbe:
            httpGet:
              path: /api/health
              port: http-api
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http-api
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
