apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . | default .Chart.Name }}-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.api.service.port }}"
  labels:
    app: {{ include "my-app.name" . | default .Chart.Name }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.containerPort }}
      protocol: TCP
      name: http-api
  selector:
    app: {{ include "my-app.name" . | default .Chart.Name }}
    component: api
